# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14hLt9a9e2d0p6BrnWgGjt1q2_pcPxnPB
"""

a = input('Enter your first name: ');
b = input('Enter your last name: ');
print('Hello, ' + a + ' ' + b + '! Welcome to the Python Program.');