# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXPWI_PDWkuKPaUuFC9Xvd1-efPgls_G
"""

a = input('Enter the first Number: ');
b = input('Enter the second Number: ');
a=int(a);
b=int(b);
print('Addition: ', a+b);
print('Subtraction: ', a-b);
print('Multiplication: ', a*b);
print('Division: ', a/b);